In [15]:
#載入library
from sklearn import datasets
import pandas as pd
import numpy as np

In [16]:
iris = datasets.load_iris()

In [17]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [18]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [20]:
print(iris['data'])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [23]:
#將json格式轉成dataframe
x = pd.DataFrame(iris['data'], columns=iris['feature_names'])
y = pd.DataFrame(iris['target'], columns=['target_names'])
#用pandas的concat()函式併起來，水平合併=1
data = pd.concat([x,y], axis=1)

In [24]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target_names  
0               0  
1               0  
2               0  
3               0  
4               0  
..            ...  
145             2  
146             2  
147             2  
148             2  
149             2  

[150 rows x 5 columns]

# DataFrame Basic Information(DataFrame 基本資訊)

In [27]:
#查看有沒有空值
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target_names       150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [28]:
data.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  target_names  
count        150.000000    150.000000  
mean           1.199333      1.000000  
std            0.762238      0.819232  
min            0.100000      0.000000  
25%            0.300000      0.000000  
50%            1.300000      1.000000  
75%            1.800000      2.000000  
max            2.500000      2.000000

In [30]:
data.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target_names'],
      dtype='object')

In [31]:
data.sort_values(by='petal length (cm)').head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
22                4.6               3.6                1.0               0.2   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   
35                5.0               3.2                1.2               0.2   
36                5.5               3.5                1.3               0.2   

    target_names  
22             0  
13             0  
14             0  
35             0  
36             0

# Data Selection

In [33]:
data['sepal length (cm)'][3:5]

3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

In [34]:
data[0:5]['sepal length (cm)']

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

In [36]:
data[['sepal length (cm)','sepal width (cm)']].head(5)

sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1
4                5.0               3.6

In [37]:
data[['sepal length (cm)','sepal width (cm)']][5:10]

sepal length (cm)  sepal width (cm)
5                5.4               3.9
6                4.6               3.4
7                5.0               3.4
8                4.4               2.9
9                4.9               3.1

In [39]:
data[5:10][['sepal length (cm)','sepal width (cm)']]

sepal length (cm)  sepal width (cm)
5                5.4               3.9
6                4.6               3.4
7                5.0               3.4
8                4.4               2.9
9                4.9               3.1

In [40]:
data.loc[5:10,['sepal length (cm)','sepal width (cm)']]

sepal length (cm)  sepal width (cm)
5                 5.4               3.9
6                 4.6               3.4
7                 5.0               3.4
8                 4.4               2.9
9                 4.9               3.1
10                5.4               3.7

# Data Selection with condition(資料篩選)

In [41]:
data[data['sepal length (cm)']>7]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
102                7.1               3.0                5.9               2.1   
105                7.6               3.0                6.6               2.1   
107                7.3               2.9                6.3               1.8   
109                7.2               3.6                6.1               2.5   
117                7.7               3.8                6.7               2.2   
118                7.7               2.6                6.9               2.3   
122                7.7               2.8                6.7               2.0   
125                7.2               3.2                6.0               1.8   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
135                7.7               3.0                6.1               2.3   

     target_names  
102             2  
105             2  
107             2  
109             2  
117             2  
118             2  
122             2  
125             2  
129             2  
130             2  
131             2  
135             2

In [43]:
data[data['target_names'].isin([1,2])]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target_names  
50              1  
51              1  
52              1  
53              1  
54              1  
..            ...  
145             2  
146             2  
147             2  
148             2  
149             2  

[100 rows x 5 columns]

# Data Calculation(資料運算)

In [44]:
data.apply(lambda x:x+1).head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                6.1               4.5                2.4               1.2   
1                5.9               4.0                2.4               1.2   
2                5.7               4.2                2.3               1.2   
3                5.6               4.1                2.5               1.2   
4                6.0               4.6                2.4               1.2   

   target_names  
0             1  
1             1  
2             1  
3             1  
4             1

In [45]:
data['sepal length (cm)'].apply(lambda x:x+2).head(5)

0    7.1
1    6.9
2    6.7
3    6.6
4    7.0
Name: sepal length (cm), dtype: float64

In [46]:
data['sepal length (cm)'].map(lambda x:x+2).head(5)

0    7.1
1    6.9
2    6.7
3    6.6
4    7.0
Name: sepal length (cm), dtype: float64

In [47]:
#apply對整個表格做運算
data.apply(lambda x:x+3).head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                8.1               6.5                4.4               3.2   
1                7.9               6.0                4.4               3.2   
2                7.7               6.2                4.3               3.2   
3                7.6               6.1                4.5               3.2   
4                8.0               6.6                4.4               3.2   

   target_names  
0             3  
1             3  
2             3  
3             3  
4             3

In [48]:
#map無法對整個表格做運算
data.map(lambda x:x+2).head(5)

AttributeError: 'DataFrame' object has no attribute 'map'

# Data Grouping(資料分群)

In [49]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target_names  
0             0  
1             0  
2             0  
3             0  
4             0

In [50]:
data.groupby(by='target_names').sum()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target_names                                                           
0                         250.3             171.4               73.1   
1                         296.8             138.5              213.0   
2                         329.4             148.7              277.6   

              petal width (cm)  
target_names                    
0                         12.3  
1                         66.3  
2                        101.3

In [51]:
data.groupby(by='target_names').mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target_names                                                           
0                         5.006             3.428              1.462   
1                         5.936             2.770              4.260   
2                         6.588             2.974              5.552   

              petal width (cm)  
target_names                    
0                        0.246  
1                        1.326  
2                        2.026

In [52]:
for i in data.groupby(by='target_names'):
    print(i)

(0,     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               

In [54]:
data.groupby(by='target_names').apply(lambda x:x.sort_values(by=['sepal length (cm)'],ascending=False)[1:2])

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target_names                                                               
0            18                 5.7               3.8                1.7   
1            52                 6.9               3.1                4.9   
2            135                7.7               3.0                6.1   

                  petal width (cm)  target_names  
target_names                                      
0            18                0.3             0  
1            52                1.5             1  
2            135               2.3             2

In [55]:
data[data['target_names']==0]['sepal length (cm)'].sort_values()

13    4.3
8     4.4
38    4.4
42    4.4
41    4.5
22    4.6
3     4.6
47    4.6
6     4.6
2     4.7
29    4.7
24    4.8
30    4.8
12    4.8
11    4.8
45    4.8
9     4.9
37    4.9
34    4.9
1     4.9
40    5.0
35    5.0
43    5.0
26    5.0
25    5.0
49    5.0
4     5.0
7     5.0
23    5.1
46    5.1
44    5.1
39    5.1
19    5.1
17    5.1
21    5.1
0     5.1
32    5.2
28    5.2
27    5.2
48    5.3
16    5.4
31    5.4
10    5.4
20    5.4
5     5.4
36    5.5
33    5.5
18    5.7
15    5.7
14    5.8
Name: sepal length (cm), dtype: float64